# Generated by Django 5.2 on 2025-04-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rate_image',
            new_name='rate_star',
        ),
    ]
